---
- hosts: second_host
  become: true

  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install PHP packages
    apt:
      name:
      - php8.1
      - php-mbstring
      - php-cli
      - php-fpm
      - php-mysql
      - php-curl
      - php-intl
      - php-xml
      state: present

  - name: Restart PHP-FPM service
    service:
      name: php8.1-fpm # Adjust this based on your PHP version
      state: restarted

