---
- name: Установка PostgreSQL-16 на сервер mowertii-vm-1
  hosts: first_host
  become: true
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        when: ansible_os_family == 'Debian'
    - name: Install PostgreSQL dependencies
      package:
        name:
          - build-essential
          - libreadline-dev
          - zlib1g-dev
          - flex
          - bison
          - libxml2-dev
          - libxslt1-dev
          - libssl-dev
          - libpq-dev
        state: present
    - name: Download PostgreSQL source code
      get_url:
        url: https://ftp.postgresql.org/pub/source/v16.0/postgresql-16.0.tar.gz
        dest: /tmp/postgresql-16.0.tar.gz
    - name: Extract PostgreSQL source code
      unarchive:
        src: /tmp/postgresql-16.0.tar.gz
        dest: /tmp/
        remote_src: yes
    - name: Configure PostgreSQL
      command: >
        ./configure --prefix=/usr/local/pgsql-16.0 --without-readline
        --without-zlib --without-bonjour --without-ldap --without-libxml
        --without-libxslt --with-openssl --with-pam --with-perl --with-python
        PYTHON=/usr/bin/python3
      args:
        chdir: /tmp/postgresql-16.0/
    - name: Build and install PostgreSQL
      command: |
        make && make install
      args:
        chdir: /tmp/postgresql-16.0/
    - name: Create PostgreSQL data directory
      file:
        path: /usr/local/pgsql-16.0/data
      state: directory
    - name: Initialize PostgreSQL database cluster
      command: |
        /usr/local/pgsql-16.0/bin/initdb -D /usr/local/pgsql-16.0/data
    - name: Start PostgreSQL service
      systemd:
        name: postgresql-16
        state: started
        enabled: yes
    - name: Set PostgreSQL environment variables
      lineinfile:
        path: /etc/profile.d/postgresql.sh
        line: export PATH=$PATH:/usr/local/pgsql-16.0/bin
        create: yes
    - name: Reload shell environment
      command: |
        source /etc/profile.d/postgresql.sh
    - name: Configure PostgreSQL authentication
      template:
        src: pg_hba.conf.j2
        dest: /usr/local/pgsql-16.0/data/pg_hba.conf
    - name: Restart PostgreSQL service for configuration changes to take effect
      systemd:
        name: postgresql-16
        state: restarted

