---
- name: Install Zabbix Agent
  hosts: virtcent
  become: true

  tasks:
  - name: Install Zabbix Agent package
    package:
      name: zabbix-agent
      state: present

  - name: Configure Zabbix agent
    template:
      src: templates/zabbix_agentd.conf.j2
      dest: /etc/zabbix_agentd.conf
    notify:
    - restart zabbix-agent

  - name: Enable and start Zabbix Agent service
    service:
      name: zabbix-agent
      state: started
      enabled: true


  handlers:
  - name: restart zabbix-agent
    service:
      name: zabbix-agent
      state: restarted


